menu:
    Blog: /
    Archive: /archives/
    Tag: /tags/
    # Weibo: http://weibo.com/cglcgl000
    GitHub: https://github.com/GLChan
    # Rss: /atom.xml

favicon: /favicon2.jpg
logo: /favicon2.jpg

# Comment
# e.g disqus: seansun
disqus: GLChen
duoshuo: glchen

# Analytics
# google-analytics:
ga: UA-71319829-1

# Copyright Infomation
startyear: 2016
